
components:
  schemas:
    CarCreateRequest:
      type: object
      properties:
        brand:
          type: string
          pattern: "^[A-Z]{1}[a-z]*( [A-Z]{1}[a-z]*)*$"
        country:
          type: string
          Pattern: "^[A-Z]{1}[a-z]*( [A-Z]{1}[a-z]*)*$"
      required:
        - brand
        - country

    CarUpdateRequest:
      $ref: "#/components/schemas/CarCreateRequest"
